/**
 * generate_blog_meta.mjs
 *
 * Generates pre-rendered HTML files for blog posts with Open Graph and Twitter Card
 * meta tags. This is necessary because the app is a client-side SPA and social media
 * crawlers (Twitter/X, Facebook, LinkedIn) don't execute JavaScript.
 *
 * Instead of creating redirect pages, this script copies the SPA's index.html and
 * injects OG meta tags into the <head>. This way:
 * - Crawlers see the meta tags in the initial HTML
 * - Real users get the full SPA which boots normally and renders the blog
 *
 * Usage: node generate_blog_meta.mjs [--data-dir <path>] [--output-dir <path>] [--base-url <url>] [--data-base-url <url>]
 */

import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

// Parse CLI arguments
const args = process.argv.slice(2);
function getArg(name, defaultValue) {
	const idx = args.indexOf(`--${name}`);
	return idx !== -1 && args[idx + 1] ? args[idx + 1] : defaultValue;
}

const dataDir = getArg('data-dir', 'static/db');
const outputDir = getArg('output-dir', 'build');
const baseUrl = getArg('base-url', 'https://hadithhub.com');
const dataBaseUrl = getArg('data-base-url', 'https://gibreelabdullah.github.io/hadith-db/data');
const defaultImage = 'https://cdn.jsdelivr.net/gh/GibreelAbdullah/Hadith-Hub@master/Header.jpg';

// Read the SPA's index.html as the base template
const indexHtmlPath = join(outputDir, 'index.html');
if (!existsSync(indexHtmlPath)) {
	console.error(`Error: index.html not found at ${indexHtmlPath}. Run the SvelteKit build first.`);
	process.exit(1);
}
const spaHtml = readFileSync(indexHtmlPath, 'utf-8');

// Read blogs manifest
const blogsJsonPath = join(dataDir, 'blogs', 'blogs.json');
if (!existsSync(blogsJsonPath)) {
	console.error(`Error: blogs.json not found at ${blogsJsonPath}`);
	process.exit(1);
}

const blogs = JSON.parse(readFileSync(blogsJsonPath, 'utf-8'));
console.log(`Found ${blogs.length} blog post(s) to generate meta pages for.`);

for (const blog of blogs) {
	const { slug, title, description, author, date } = blog;
	const url = `${baseUrl}/blogs/${slug}`;

	// Check if there's a blog-specific OG image (try .png then .jpg)
	const blogImagePng = join(dataDir, 'blogs', `${slug}.png`);
	const blogImageJpg = join(dataDir, 'blogs', `${slug}.jpg`);
	let ogImage = defaultImage;
	if (existsSync(blogImagePng)) {
		ogImage = `${dataBaseUrl}/blogs/${slug}.png`;
	} else if (existsSync(blogImageJpg)) {
		ogImage = `${dataBaseUrl}/blogs/${slug}.jpg`;
	}

	// Build the meta tags to inject
	const metaTags = `
  <!-- Blog OG Meta Tags (generated by generate_blog_meta.mjs) -->
  <title>${escapeHtml(title)} | HadithHub</title>
  <meta name="description" content="${escapeHtml(description)}" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="${url}" />
  <meta property="og:title" content="${escapeHtml(title)}" />
  <meta property="og:description" content="${escapeHtml(description)}" />
  <meta property="og:image" content="${ogImage}" />
  <meta property="og:site_name" content="HadithHub" />
  <meta property="article:published_time" content="${date}" />
  <meta property="article:author" content="${escapeHtml(author)}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:url" content="${url}" />
  <meta name="twitter:title" content="${escapeHtml(title)}" />
  <meta name="twitter:description" content="${escapeHtml(description)}" />
  <meta name="twitter:image" content="${ogImage}" />
  <!-- End Blog OG Meta Tags -->`;

	// Inject meta tags right after the opening <head> tag and existing meta charset
	const html = spaHtml.replace(
		/(<head>[\s\S]*?<meta charset="utf-8" \/>)/,
		`$1${metaTags}`
	);

	// Write to build/blogs/<slug>/index.html
	const outputPath = join(outputDir, 'blogs', slug, 'index.html');
	mkdirSync(join(outputDir, 'blogs', slug), { recursive: true });
	writeFileSync(outputPath, html, 'utf-8');
	console.log(`  ✓ Generated: ${outputPath}`);
}

console.log(`\nDone! Generated ${blogs.length} blog meta page(s).`);

function escapeHtml(str) {
	return str
		.replace(/&/g, '&amp;')
		.replace(/"/g, '&quot;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;');
}
